In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import f_regression
sns.set()

In [2]:
df=pd.read_csv('simple_linear_regression.csv')

In [3]:
x=df.iloc[:,0]
y=df.iloc[:,1]

x_matrix=x.values.reshape(-1,1)

In [4]:
reg=LinearRegression()
reg.fit(x_matrix,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [5]:
reg.score(x_matrix,y)

0.40600391479679765

In [6]:
reg.coef_

array([0.00165569])

In [7]:
reg.intercept_

0.275040299660279

In [8]:
reg.predict([[1740]])

array([3.15593751])

In [9]:
df1=pd.read_csv(r'C:\Users\admin\Desktop\1.02.%20Multiple%20linear%20regression.csv')

In [10]:
df1.head(2)

SAT   GPA  Rand 1,2,3
0  1714  2.40           1
1  1664  2.52           3

In [11]:
x=df1.iloc[:,[0,2]]
y=df1.iloc[:,1]

In [12]:
reg=LinearRegression()
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [13]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [14]:
reg.intercept_

0.29603261264909353

In [15]:
reg.score(x,y)

0.40668119528142815

In [16]:
r2=reg.score(x,y)
n=x.shape[0]
p=x.shape[1]
adjusted_r2=1-(1-r2)*(n-1)/(n-p-1)

In [17]:
adjusted_r2

0.39203134825134

In [18]:
p_values=f_regression(x,y)[1]
p_values.round(3)

array([0.   , 0.676])

In [19]:
reg_summary=pd.DataFrame(data=x.columns.values,columns=['features'])

In [20]:
reg_summary['Coefficients']=reg.coef_
reg_summary['P values']=p_values.round(3)
reg_summary

features  Coefficients  P values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676

In [21]:
from sklearn.preprocessing import StandardScaler

In [22]:
scaler=StandardScaler()
scaler.fit(x)
x_scaled=scaler.transform(x)